### ISSUE TITLE
Error running composer

### ISSUE THREAD

**Issue by plicas** [dipit2007/larastore#7]
After running composer for the first time i got an error:
Declaration of Amsgames\LaravelShop\LaravelShopProvider::boot() should be compatible with Illuminate\Foundation\Support\Providers\RouteServiceProvider::boot()

**Comment by plicas** [comment]
I solve the issue changing the boot to:
`  public function boot()
    {
      \Route::pattern('domain', '[a-z0-9.\-]+');
      parent::boot();

        // Publish config files
        $this->publishes([
            __DIR__ . '/Config/config.php' => config_path('shop.php'),
        ]);

        // Register commands
        $this->commands('command.laravel-shop.migration');

    }`

I also had to change the "bindshare" to singleton on line 92.

**Comment by dipit2007** [comment]
Hi, is it useful to you.I started this to make complete e Commerce solution base on Laravel. I was busy due to some personal issue. Will update shortly. Thanks  a lot for sharing interest on this.
